### ISSUE TITLE
Add Playwright example

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#109]
The Playwright example needs to be changed to work with the newest wrapped Playwright code and should include an example for automatic mode and one for manual mode, as well as have all dependancies updated (i.e. use Cypress 12)

**Comment by SantoshDeque** [comment]
Pulled  the latest watcher-example repo for playwright, but in manual mode `wrapPlaywright` is missing in below 2 places
1)at the top of test file
2)Within the Before hook of test file

<img width="1150" alt="Screenshot 2023-05-22 at 1 25 53 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/ba225ed4-9159-4de9-a688-1e78cccf6893">


https://github.com/dequelabs/watcher-examples/assets/45222788/245d4d95-127a-4a0c-a22c-8f23cb6c1181

**Comment by Zidious** [comment]
We do not _need_ to have `wrapPlaywright` for manual mode as we call `controller.analyze()` whenever we want to analyze. I guess this is more of a consistency question. @dequejenn shall we remove them from the this from the docs on the start up?

**Comment by dequejenn** [comment]
Moving to backlog since we are not prioritizing manual mode at the moment (removing it from the UI)

**Comment by dequejenn** [comment]
Removing manual mode from this scope so this ticket can be QA'd (manual mode on hold). QA - please only QA the auto basic example here. Thanks!

**Comment by padmavemulapati** [comment]
Tested only for auto basic example, working as expected.


https://github.com/dequelabs/watcher-examples/assets/47409579/0d6b6420-a9d3-452f-aa15-593f17008f34

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.82.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.099d5645_ |
|**Playwright** |_1.33.0_ |
