### ISSUE TITLE
Create multi-page TS example for playwright

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#133]
Create a multi-page test in playwright in typescript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by SantoshDeque** [comment]
Verified with latest watcher-examples repo(https://github.com/dequelabs/watcher-examples.git), multip-page TS example for playwright(playwright/typescript-multi-page) is added and is working as expected.

https://github.com/dequelabs/watcher-examples/assets/45222788/79c46c5c-2c92-4d74-9a49-41741e47e982

## Branches
<img width="1325" alt="Screenshot 2023-06-01 at 3 08 16 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/12f54af0-9662-4603-bfe3-e741803a6782">


## Commits
<img width="1281" alt="Screenshot 2023-06-01 at 3 08 25 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/1b25ee6f-cef0-4515-8a5b-d4614ee3a126">


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.82.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.fd1cc39e_ |
