### ISSUE TITLE
Create basic JS example for playwright w/config

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#134]
Create a simple test in playwright w/config in javascript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by SantoshDeque** [comment]
Verified with latest watcher-examples repo(https://github.com/dequelabs/watcher-examples.git), basic JS example for is added(playwright-test/basic) and is working as expected.

https://github.com/dequelabs/watcher-examples/assets/45222788/da300393-9973-4d07-9e01-48d62bdcadd7


## Mutliple commits:
https://axe.dequelabs.com/axe-watcher/projects/b67c6bcd-1334-4fb2-8f20-87991431f04b/branches/main/commits
<img width="1440" alt="Screenshot 2023-05-31 at 7 16 50 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/f6377148-53e8-4c77-a4b5-6d4273519890">


## Multiple Branches:
https://axe.dequelabs.com/axe-watcher/projects/b67c6bcd-1334-4fb2-8f20-87991431f04b/branches
<img width="1440" alt="Screenshot 2023-05-31 at 7 19 38 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/633ed2ea-bf0b-41f9-bff3-aabe0df1726c">
