### ISSUE TITLE
Create multi-page TS example for Playwright w/config

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#135]
Create a multi-page test in playwright w/config in typescript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by SantoshDeque** [comment]
Verified with latest watcher-examples repo(https://github.com/dequelabs/watcher-examples.git), multip-page TS example for playwright-test is added and is working as expected.

https://github.com/dequelabs/watcher-examples/assets/45222788/c6bfaba3-d44c-4124-a7c3-5f25d6f8921a


<img width="1440" alt="Screenshot 2023-05-31 at 4 54 08 PM" src="https://github.com/dequelabs/watcher-examples/assets/45222788/ebd0c010-525e-4368-900f-6772ae959fd7">


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.82.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.eb000163_ |
