### ISSUE TITLE
Create basic JS example for Puppeteer

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#136]
Create a simple test in Puppeteer in javascript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by padmavemulapati** [comment]
Verfied with the latest puppeteer-single page - basic `js`example, 
1. Enabled Puppeteer_v1 feature flag
2. Created a Puppeteer project
3. From `watcher-example` /puppeteer/basic/tests/login.js
4. Verified the instructions from "developer-hub" `start-up` page `instrucitons` matched with the `example-login.js`  
5. Updated `API-key` and `server-url`
Working as expected

https://github.com/dequelabs/watcher-examples/assets/47409579/cd75cac7-d1eb-4745-9845-1e756caf3daf

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.82.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.e32d348e_ |
