### ISSUE TITLE
Create multi-page TS example for Puppeteer

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#137]
Create a multi-page test in Puppeteer in typescript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by stephenmathieson** [comment]
Be sure you have the `@next` version installed. The v2.0.0 version doesn't support wrapping Puppeteer yet.

**Comment by padmavemulapati** [comment]
@stephenmathieson - verified with the `2.0.0-next.91190bb6` , today's `@next` version



![Image](https://github.com/dequelabs/watcher-examples/assets/47409579/319240c6-5db0-4c0f-ba89-9985603aa922)

**Comment by padmavemulapati** [comment]
> Be sure you have the `@next` version installed. The v2.0.0 version doesn't support wrapping Puppeteer yet.

Yes Stephen, Thank you , now updated to `2.0.0-next.e2ca8d21` - no error now.
