### ISSUE TITLE
Create basic JS example for WebDriverJS

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#144]
Create a simple test for WebDriverJS in javascript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by padmavemulapati** [comment]
WebdriverJS project is working as expected, but everywhere, it is appearing as "selenium" instead "webdriverJS" . Moving back to "Bugs" column to make the neccessary changes

**Comment by padmavemulapati** [comment]
Verified , "Selenium"changed to "WebdriverJS" and card displaying with "Selenium-Webdriverjs" as show in the screenshot:
<img width="894" alt="image" src="https://github.com/dequelabs/jazzband/assets/47409579/b050fb6e-c565-4340-9899-28a9e7dc44e1">

https://github.com/dequelabs/watcher-examples/assets/47409579/b9cec31d-703b-4b8b-85ac-2be032bbf6aa




## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.83.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.d13b50c3_ |
|**Browser details** | _Chrome Version 114.0.5735.110 & Firefox114.0.1 (64-bit)_ |
