### ISSUE TITLE
Create multi-page TS example for WebDriverJS

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#145]
Create a multi-page test using WebDriverJS in typescript that already has Watcher integrated into it. When run, the test should result in a few accessibility errors. Verify these results make it up to developer hub and are expected and consistent before closing this ticket.

**Comment by padmavemulapati** [comment]
"Selenium" appearing instead "WebdriverJS" everywhere. So moving it back to reopen for the expected change implementation

**Comment by padmavemulapati** [comment]
Verified , multi-page example is working as expected and instructions updated to webdriverjs example.


https://github.com/dequelabs/watcher-examples/assets/47409579/97052e6c-0a6a-4fa4-8ef8-71f5c1f6294b

## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.83.0_ |
| **@axe-core/watcher version**      | _2.0.0-next.d13b50c3_ |
|**Browser details** | _Chrome Version 114.0.5735.110 & Firefox114.0.1 (64-bit)_ |
