### ISSUE TITLE
Update Puppeteer Examples 

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#161]
Once this ticket is completed and released, please update the Puppeteer examples to use the new integration.

https://github.com/dequelabs/jazzband/issues/647

**Comment by Zidious** [comment]
This required https://github.com/dequelabs/axe-test-fixtures/pull/24 - This PR adds watcher fixtures

**Comment by Zidious** [comment]
ref: https://github.com/dequelabs/watcher-examples/pull/166

**Comment by padmavemulapati** [comment]
Verified with the latest  [watcher-examples](https://github.com/dequelabs/watcher-examples) , Puppeteer instrucitons updated.
and working as expected.



https://github.com/dequelabs/watcher-examples/assets/47409579/27f9075e-a31d-4a07-a623-23f694c0fd55


## Environment:
| **Label**                         | **Value** |
| -------------------------- | ------ |
| **Server URL**                | _https://axe.dequelabs.com/_ |
| **Server version**           | _4.91.0_ |
| **@axe-core/watcher version**      | _3.1.0-next.0f183a45_ |
| **OS-Details**      |  _MAC- Intel Core i7 - 11.6.8_ |
|**BrowserDetails**|_Chrome Version 116.0.5845.110 (Official Build) (64-bit)_|
