### ISSUE TITLE
BUG: Flush() method is missing in watcher-examples repo for webdriverJS basic test

### ISSUE THREAD

**Issue by gayathrit12** [dequelabs/watcher-examples#177]
## Issue Description: 
In WebdriverJS basic test, Flush() method is missing in watcher-examples repo where as it is present in instructions page, because of which even the test passes the results are not being flushed. 

### watcher-example repo:

![image](https://github.com/dequelabs/watcher-examples/assets/102580833/ca9275e6-972b-4485-8746-451acd0896fb)

Repo-link: https://github.com/dequelabs/watcher-examples/blob/main/webdriverjs/basic/tests/login.js

### Instructions page:
![image](https://github.com/dequelabs/watcher-examples/assets/102580833/2d597db2-0927-425d-8367-f57b6eb267e4)

**Comment by padmavemulapati** [comment]
Verified in the latest watcher-examples code, webdriverjs login script is updated with 

```
 afterEach(async () => {
    await controller.flush()
  })
```

<img width="672" alt="image" src="https://github.com/dequelabs/watcher-examples/assets/47409579/52629a01-56a9-4a32-87aa-b1346311882f">

Resutls:
<img width="1315" alt="image" src="https://github.com/dequelabs/watcher-examples/assets/47409579/2aeb7a3f-9d54-486d-a214-9232fd028cbb">

## Environment:
| **Label**                        | **Value** |
| -------------------------- | ------ |
| **Product**               | _Devhub Examples_ |
|**Version** | _3.11.0_ |
|**axe-core/watcher-webdriverjs**|_selenium-webdriver_4.22.0_|
| **OS-Details**     | _MAC- 14.4.1 _ |
|**BrowserDetails**|_Chrome Version 126.0.4 _|
