### ISSUE TITLE
Update `cy.axeFlush()` to `cy.axeWatcherFlush()` in all cypress tests

### ISSUE THREAD

**Issue by dequejenn** [dequelabs/watcher-examples#186]
We are deprecating `cy.axeFlush()` and that needs to be reflected in the Cypress examples:

- [ ] https://github.com/dequelabs/watcher-examples/blob/a54beef0d65d0bc8a1656d1f349725037e955f49/cypress/basic/cypress/support/e2e.js#L6
- [ ] https://github.com/dequelabs/watcher-examples/blob/a54beef0d65d0bc8a1656d1f349725037e955f49/cypress/iframes/cypress/support/e2e.js#L6
- [ ] https://github.com/dequelabs/watcher-examples/blob/a54beef0d65d0bc8a1656d1f349725037e955f49/cypress/manual-mode/cypress/support/e2e.js#L6
- [ ] https://github.com/dequelabs/watcher-examples/blob/a54beef0d65d0bc8a1656d1f349725037e955f49/cypress/multi-page/cypress/support/e2e.js#L6

**Comment by davidg-dq** [comment]
Looks like @Zidious took care of this last month.
![image](https://github.com/dequelabs/watcher-examples/assets/172271162/5be543b6-c482-45be-aa97-3390445aaa0a)
